name: Deploy
on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  Deploy:
    uses: seanh/ghp-pelican/.github/workflows/pelican.yml@1a2945f80a9a23ddee7b0446f1cb26bd8b3a0bcc
    permissions:
      contents: read
      pages: write
      id-token: write
    with:
      settings: "publishconf.py"
      theme: "https://github.com/seanh/sidecar.git"
