name: Deploy
on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  Deploy:
    uses: seanh/ghp-pelican/.github/workflows/pelican.yml@84af133ff02c740337d769cb18a65c5c30d622f8
    permissions:
      contents: read
      pages: write
      id-token: write
    with:
      settings: "publishconf.py"
      requirements: "pelican[markdown] typogrify"
      theme: "https://github.com/seanh/sidecar.git"
